create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  title text not null,
  summary text not null default '',
  description text not null default '',
  image_url text not null default '',
  link_url text not null default '#',
  sort_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.site_events enable row level security;

drop policy if exists "Public can read active site events" on public.site_events;
create policy "Public can read active site events"
on public.site_events
for select
to anon
using (is_active = true);
