"use strict";

/* ===== scripts/utils/dom.js ===== */

function getElements() {
  return {
    turnBadge: document.querySelector("#turnBadge"),
    playersList: document.querySelector("#playersList"),
    openCardsGuideBtn: document.querySelector("#openCardsGuideBtn"),
    openReviewsBtn: document.querySelector("#openReviewsBtn"),
    authStatus: document.querySelector("#authStatus"),
    loginControls: document.querySelector("#loginControls"),
    loginInput: document.querySelector("#loginInput"),
    passwordInput: document.querySelector("#passwordInput"),
    loginBtn: document.querySelector("#loginBtn"),
    logoutBtn: document.querySelector("#logoutBtn"),
    diceResult: document.querySelector("#diceResult"),
    chatDiceResult: document.querySelector("#chatDiceResult"),
    playerSummary: document.querySelector("#playerSummary"),
    reviewPanel: document.querySelector("#reviewPanel"),
    reviewSectorHint: document.querySelector("#reviewSectorHint"),
    reviewTitleInput: document.querySelector("#reviewTitleInput"),
    reviewRatingInput: document.querySelector("#reviewRatingInput"),
    reviewTypeInput: document.querySelector("#reviewTypeInput"),
    reviewTextInput: document.querySelector("#reviewTextInput"),
    saveReviewBtn: document.querySelector("#saveReviewBtn"),
    selectedHint: document.querySelector("#selectedHint"),
    openRulesBtn: document.querySelector("#openRulesBtn"),
    openGameRulesBtn: document.querySelector("#openGameRulesBtn"),
    openSectorInfoBtn: document.querySelector("#openSectorInfoBtn"),
    editSectorBtn: document.querySelector("#editSectorBtn"),
    board: document.querySelector("#board"),
    cardsList: document.querySelector("#cardsList"),
    chatCardsList: document.querySelector("#chatCardsList"),
    drawCardBtn: document.querySelector("#drawCardBtn"),
    drawChatCardBtn: document.querySelector("#drawChatCardBtn"),
    clearLogBtn: document.querySelector("#clearLogBtn"),
    eventLog: document.querySelector("#eventLog"),
    resetGameBtn: document.querySelector("#resetGameBtn"),
    saveSlotBtn: document.querySelector("#saveSlotBtn"),
    saveSlots: document.querySelector("#saveSlots"),
    exportBtn: document.querySelector("#exportBtn"),
    importInput: document.querySelector("#importInput"),
    rollBtn: document.querySelector("#rollBtn"),
    openCardWheelBtn: document.querySelector("#openCardWheelBtn"),
    openCustomWheelBtn: document.querySelector("#openCustomWheelBtn"),
    cardWheelDialog: document.querySelector("#cardWheelDialog"),
    customWheelDialog: document.querySelector("#customWheelDialog"),
    closeCardWheelBtn: document.querySelector("#closeCardWheelBtn"),
    closeCustomWheelBtn: document.querySelector("#closeCustomWheelBtn"),
    cardWheelDisk: document.querySelector("#cardWheelDisk"),
    customWheelDisk: document.querySelector("#customWheelDisk"),
    cardWheelDurationInput: document.querySelector("#cardWheelDurationInput"),
    customWheelDurationInput: document.querySelector("#customWheelDurationInput"),
    cardWheelResult: document.querySelector("#cardWheelResult"),
    customWheelInput: document.querySelector("#customWheelInput"),
    customWheelResult: document.querySelector("#customWheelResult"),
    spinCardWheelBtn: document.querySelector("#spinCardWheelBtn"),
    spinCustomWheelBtn: document.querySelector("#spinCustomWheelBtn"),
    diceDialog: document.querySelector("#diceDialog"),
    diceDialogTitle: document.querySelector("#diceDialogTitle"),
    diceOne: document.querySelector("#diceOne"),
    diceTwo: document.querySelector("#diceTwo"),
    sectorInfoDialog: document.querySelector("#sectorInfoDialog"),
    sectorInfoTitle: document.querySelector("#sectorInfoTitle"),
    sectorInfoBody: document.querySelector("#sectorInfoBody"),
    closeSectorInfoBtn: document.querySelector("#closeSectorInfoBtn"),
    sectorDialog: document.querySelector("#sectorDialog"),
    sectorDialogTitle: document.querySelector("#sectorDialogTitle"),
    closeSectorDialogBtn: document.querySelector("#closeSectorDialogBtn"),
    cancelSectorBtn: document.querySelector("#cancelSectorBtn"),
    saveSectorBtn: document.querySelector("#saveSectorBtn"),
    sectorNameInput: document.querySelector("#sectorNameInput"),
    sectorTypeInput: document.querySelector("#sectorTypeInput"),
    sectorColorInput: document.querySelector("#sectorColorInput"),
    sectorPointsInput: document.querySelector("#sectorPointsInput"),
    sectorTaglineInput: document.querySelector("#sectorTaglineInput"),
    sectorDescriptionInput: document.querySelector("#sectorDescriptionInput"),
    sectorActionInput: document.querySelector("#sectorActionInput"),
    sectorActionValueInput: document.querySelector("#sectorActionValueInput"),
    rulesDialog: document.querySelector("#rulesDialog"),
    closeRulesBtn: document.querySelector("#closeRulesBtn"),
    rulesBody: document.querySelector("#rulesBody"),
    gameRulesDialog: document.querySelector("#gameRulesDialog"),
    closeGameRulesBtn: document.querySelector("#closeGameRulesBtn"),
    gameRulesBody: document.querySelector("#gameRulesBody"),
    reviewsDialog: document.querySelector("#reviewsDialog"),
    closeReviewsBtn: document.querySelector("#closeReviewsBtn"),
    reviewsBody: document.querySelector("#reviewsBody"),
    cardsGuideDialog: document.querySelector("#cardsGuideDialog"),
    closeCardsGuideBtn: document.querySelector("#closeCardsGuideBtn"),
    cardsGuideBody: document.querySelector("#cardsGuideBody"),
  };
}
function openDialog(dialog) {
  if (!dialog) return;
  if (typeof dialog.showModal === "function") dialog.showModal();
  else dialog.setAttribute("open", "");
}
function closeDialog(dialog) {
  if (dialog?.open) dialog.close();
}
